- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.4.4
  hooks:
  - id: autopep8
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md, --markdown-linebreak-ext=feature]
  - id: check-json
  - id: pretty-format-json
    args: [--autofix, --indent=2]
- repo: https://github.com/shopozor/pre-commit-hooks
  rev: master
  hooks:
    - id: check-feature-tags