# Generated by Django 2.1.5 on 2019-01-25 08:14

from django.db import migrations


def add_shopozor_permissions(apps, schema_editor):
    User = apps.get_model('account', 'User')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    ct = ContentType.objects.get_for_model(User)
    Permission.objects.create(codename='manage_producers', name='Can manage producers', content_type=ct)
    Permission.objects.create(codename='manage_managers', name='Can manage managers', content_type=ct)
    Permission.objects.create(codename='manage_rex', name='Can manage rex', content_type=ct)


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20181011_0737'),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name')
    ]

    operations = [
        migrations.RunPython(add_shopozor_permissions)
    ]
