# Generated by Django 2.2.3 on 2019-07-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0095_auto_20190618_0842'),
        ('shopozor', '0003_auto_20190226_0721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('product_variants', models.ManyToManyField(blank=True,
                                                            related_name='catalogues', to='product.ProductVariant')),
            ],
        ),
    ]
