# Generated by Django 2.2.3 on 2019-08-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopozor', '0004_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
