# Generated by Django 2.2.3 on 2019-08-17 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_user_private_meta'),
        ('product', '0095_auto_20190618_0842'),
        ('shopozor', '0006_auto_20190817_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                              primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='shop',
            name='product_variants',
            field=models.ManyToManyField(
                blank=True, to='product.ProductVariant'),
        ),
        migrations.CreateModel(
            name='ProductStaff',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                                 primary_key=True, serialize=False, to='product.Product')),
                ('staff', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='shopozor.Staff')),
            ],
        ),
    ]
