# Generated by Django 2.2.3 on 2019-09-09 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0095_auto_20190618_0842'),
        ('shopozor', '0007_auto_20190817_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                                 primary_key=True, serialize=False, to='product.Product')),
                ('conservation_mode', models.CharField(blank=True, max_length=256)),
                ('conservation_days', models.IntegerField()),
            ],
        ),
    ]
