# Generated by Django 2.2.3 on 2019-09-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopozor', '0009_staff_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarginDefinitions',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=32)),
                ('margin', models.FloatField(default=0)),
            ],
        ),
    ]
