# Generated by Django 2.2.3 on 2019-10-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopozor', '0009_staff_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSmtpConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=1024)),
                ('port', models.PositiveSmallIntegerField(default=1025)),
                ('host_user', models.CharField(max_length=256)),
                ('host_password', models.CharField(max_length=256)),
                ('use_ssl', models.BooleanField(default=False)),
                ('use_tls', models.BooleanField(default=False)),
            ],
        ),
    ]
