# Generated by Django 2.2.3 on 2019-09-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopozor', '0010_initial_vat_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vat_rate',
            field=models.FloatField(default=0),
        ),
    ]
