# Generated by Django 2.2.3 on 2019-10-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopozor', '0011_initial_margindefinitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vat_rate',
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='margindefinitions',
            name='margin',
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=6),
        ),
    ]
