pipeline {
  agent any
  environment {
    DOCKER_CREDENTIALS = credentials('docker-credentials')
    JELASTIC_APP_CREDENTIALS = credentials('jelastic-app-credentials')
    JELASTIC_CREDENTIALS = credentials('jelastic-credentials')
    PRODUCTION_DOCKER_REPO = "softozor/shopozor-backend:$TAG"
    PATH_TO_JPS = "./production/manifest.jps"
    PRODUCTION_ENV_NAME = "shopozor-backend"
    STAGING_BRANCH = "staging"
    STAGING_DOCKER_REPO = "softozor/shopozor-backend:staging"
    STAGING_ENV_NAME = "shopozor-backend-staging"
  }
  stages {
    stage('Publish staging docker container') {
      steps {
        script {
            sh "cp production/Dockerfile production/.dockerignore ."
            sh "docker login -u $DOCKER_CREDENTIALS_USR -p $DOCKER_CREDENTIALS_PSW"
            sh "docker build --network=host -t $STAGING_DOCKER_REPO ."
            sh "docker push $STAGING_DOCKER_REPO"
        }
      }
    }
    stage('Deploy staging environment') {
      steps {
        script {
          SCRIPT_TO_RUN = './production/deploy-to-jelastic.sh'
          sh "chmod u+x $SCRIPT_TO_RUN"
          sh "dos2unix $SCRIPT_TO_RUN"
          sh "$SCRIPT_TO_RUN $JELASTIC_APP_CREDENTIALS_USR $JELASTIC_APP_CREDENTIALS_PSW $JELASTIC_CREDENTIALS_USR $JELASTIC_CREDENTIALS_PSW $STAGING_ENV_NAME cp $PATH_TO_JPS $STAGING_BRANCH"
        }
      }
    }
    // stage('Check environment') {
    // TODO: check environment stuff like ssl, DEBUG=False, ALLOWED_HOSTS, security checks, etc.
    // }
    stage('Check GraphQL endpoint') {
      environment {
        GRAPHQL_ENDPOINT = "${STAGING_ENV_NAME}.hidora.com/graphql/"
      }
      steps {
        script {
          SCRIPT_TO_RUN = './production/test-graphql.sh'
          sh "chmod u+x $SCRIPT_TO_RUN"
          sh "dos2unix $SCRIPT_TO_RUN"
          sh "$SCRIPT_TO_RUN $GRAPHQL_ENDPOINT"
        }
      }
    }
    stage('Tag staging version') {
      steps {
        script {
          sh "git tag $TAG -m $DESCRIPTION"
          sh "git push origin $TAG"
          sh "git checkout $TAG"
        }
      }
    }
    stage('Publish production docker container') {
      steps {
        script {
            sh "cp production/Dockerfile production/.dockerignore ."
            sh "docker login -u $DOCKER_CREDENTIALS_USR -p $DOCKER_CREDENTIALS_PSW"
            sh "docker build --network=host -t $PRODUCTION_DOCKER_REPO ."
            sh "docker push $PRODUCTION_DOCKER_REPO"
        }
      }
    }
    stage('Deploy production environment') {
      steps {
        script {
          SCRIPT_TO_RUN = './production/deploy-to-jelastic.sh'
          sh "chmod u+x $SCRIPT_TO_RUN"
          sh "dos2unix $SCRIPT_TO_RUN"
          sh "$SCRIPT_TO_RUN $JELASTIC_APP_CREDENTIALS_USR $JELASTIC_APP_CREDENTIALS_PSW $JELASTIC_CREDENTIALS_USR $JELASTIC_CREDENTIALS_PSW $PRODUCTION_ENV_NAME cp $PATH_TO_JPS $TAG"
        }
      }
    }
  }
}