pipeline {
  agent {
    docker {
      image 'nikolaik/python-nodejs:python3.5-nodejs12'
    }
  }
  environment {
    REPORTS_FOLDER = 'junit-reports'
    VENV = 'venv'
  }
  stages {
    stage('Virtual Environment Installation') {
      steps {
        withEnv(["HOME=$WORKSPACE"]) {
          sh "virtualenv $VENV"
          sh "chmod u+x ./scripts/install/*.sh"
          sh ". $VENV/bin/activate && ./scripts/install/install.sh"
          sh ". $VENV/bin/activate && ./scripts/install/install-dev.sh"
        }
      }
    }
    stage('Build saleor frontend') {
      steps {
        withEnv(["HOME=$WORKSPACE"]) {
          sh "cd saleor && npm i && npm run build-assets && npm run build-emails"
        }
      }
    }
    stage('Performing saleor unit tests') {
      environment {
        DATABASE_URL = credentials('postgres-credentials')
        DJANGO_SETTINGS_MODULE = 'tests.settings'
        PYTHONPATH = "$PYTHONPATH:$WORKSPACE/saleor"
      }
      steps {
        sh ". $VENV/bin/activate && cd saleor && pytest -ra --junitxml=$REPORTS_FOLDER/saleor-unit-tests.xml"
      }
    }
    stage('Performing shopozor unit tests') {
      environment {
        DATABASE_URL = credentials('postgres-credentials')
        DJANGO_SETTINGS_MODULE = 'unit_tests.settings'
        PYTHONPATH = "$PYTHONPATH:$WORKSPACE/saleor"
      }
      steps {
        sh ". $VENV/bin/activate && pytest -ra --junitxml=$REPORTS_FOLDER/shopozor-unit-tests.xml"
      }
    }
  }
  post {
    always {
      script {
         junit "**/$REPORTS_FOLDER/*.xml"
      }
    }
  }
}