def helpers = new ch.softozor.pipeline.Helpers()

pipeline {
  agent {
    docker {
      image 'python:latest'
    }
  }
  environment {
    DJANGO_SETTINGS_MODULE = 'features.settings'
    JWT_ALGORITHM = 'HS256'
    JWT_EXPIRATION_DELTA_IN_DAYS = 30
    JWT_REFRESH_EXPIRATION_DELTA_IN_DAYS = 360
    JWT_SECRET_KEY = 'test_key'
    PYTHONPATH = "$PYTHONPATH:$WORKSPACE/saleor"
    REPORTS_FOLDER = 'junit-reports'
    SECRET_KEY = 'theSecretKey'
    VENV = 'venv'
  }
  stages {
    stage('Virtual Environment Installation') {
      steps {
        withEnv(["HOME=$WORKSPACE"]) {
          sh "pip install virtualenv --user"
          sh "$WORKSPACE/.local/bin/virtualenv $VENV"
          sh ". $VENV/bin/activate && pip install dos2unix"
          sh "python venv/lib/python3.7/site-packages/dos2unix.py scripts/install/install.sh scripts/install/install.sh"
          sh "python venv/lib/python3.7/site-packages/dos2unix.py scripts/install/install-dev.sh scripts/install/install-dev.sh"
          sh "chmod u+x ./scripts/install/*.sh"
          sh ". $VENV/bin/activate && ./scripts/install/install.sh"
          sh ". $VENV/bin/activate && ./scripts/install/install-dev.sh"
        }
      }
    }
    stage('Generating fixtures') {
      steps {
        sh ". $VENV/bin/activate && python manage.py generate_django_fixtures"
      }
    }
    stage('Performing acceptance tests') {
      environment {
        DATABASE_URL = credentials('postgres-credentials')
      }
      steps {
        sh ". $VENV/bin/activate && python manage.py behave --junit --junit-directory $REPORTS_FOLDER --tags ~wip"
      }
    }
  }
  post {
    always {
      environment {
        SOFTOZOR_CREDENTIALS = credentials('softozor-credentials')
      }
      script {
        junit "**/$REPORTS_FOLDER/*.xml"
        // TODO: call that in the merger job?
        if(GIT_BRANCH == 'origin/dev' || GIT_BRANCH == 'origin/master') {
          helpers.generateSpecification("$WORKSPACE/features", 'backend', GIT_COMMIT)
        }
      }
    }
  }
}